touch-deploy:
    stage: deploy
    script:
        - apk add curl
        - "curl -X POST -F token=$RG_ANALYTICS_TRIGGER -F ref=master https://gitlab.raccoongang.com/api/v4/projects/288/trigger/pipeline"
    only:
        - master
